mq:
  server: localhost:9092
  traffic_topic: net-traffic
  event_topic: abnormal-events

traffic_gathering:
  interface: ens33
  capture_filter: tcp

Trojan:
  model_path: ./Trojan/Model/model.sav

Worm:
  model_path: ./Worm/Model/model.sav

Virus:
  model_path: ./Virus/Model/model.sav

testpath: ['./test']
deletepath: './test'