mq:
  bootstrap_servers: localhost:9092
  traffic_topic: net-traffic
  event_topic: abnormal-events
  ddos_group_id: ddos
  
abnormal_traffic:
  ddos:
    model: TrafficAnalyzer/abnomal-traffic/ddos/Models/231110_2
    encoder: TrafficAnalyzer/abnomal-traffic/ddos/Models/231110_2.enc