mq:
  bootstrap_servers: localhost:9092
  traffic_topic: net-traffic
  event_topic: abnormal-events
  ddos_group_id: ddos
  botnet_group_id: botnet
  trojan_group_id: trojan
  worm_group_id: worm
  virus_group_id: virus

abnormal_traffic:
  ddos:
    model: ./abnomal_traffic/ddos/Models/231110_2
    encoder: ./abnomal_traffic/ddos/Models/231110_2.enc
  botnet:
    model: ./abnomal_traffic/botnet/Models/model.pkl
  trojan:
    model: ./abnomal_traffic/trojan/Model/model.sav
  virus:
    model: ./abnomal_traffic/virus/Model/model.sav
  worm:
    model: ./abnomal_traffic/worm/Model/model.sav
